services:
  frontend:
    build: ./docker_next
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./docker_next:/app

  backend:
    build: ./docker_backend
    container_name: backend_container
    ports:
      - "3001:3001"
    volumes:
      - ./docker_backend:/app
    depends_on:
      - postgres


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: harishgarg.tech@gmail.com
      PGADMIN_DEFAULT_PASSWORD: harish
    ports:
      - "5050:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=harish
      - POSTGRES_PASSWORD=harish
      - POSTGRES_DB=harish
    ports:
      - "5440:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_container
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
